version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: demo
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  #store microservice
  app_store:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./storerate
    env_file: ./.env
    ports:
      - 8083:8083
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
