version: "3.8"

services:
  #---------------------------
  #NGINX
  #---------------------------
  nginx:
    container_name: nginx
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - securitygw

  #---------------------------
  #MICROSERVICES (API)
  #---------------------------
  #Store microservice
  store:
    container_name: store
    build: ./store
    expose: ["8081"]
    depends_on:
      - mysql_db
      - elastic_db

  #Storerate microservice
  storerate:
    container_name: storerate
    build: ./storerate
    expose: ["8083"]
    depends_on:
      - mysql_db

  #Securitygw microservice
  securitygw:
    container_name: securitygw
    build: ./securitygw
    expose: ["8082"]
    ports:
      - 8082:8082
    depends_on:
      - mysql_db
      - storerate
      - store
  #---------------------------
  #DATABASES
  #---------------------------
  #MySql
  mysql_db:
    container_name: mysql_db
    image: "mariadb:10.5.8"
    volumes:
      - ./database/sql:/var/lib/mysql
    expose: ["3306"]
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: prod_sdv_bdd
      MYSQL_ROOT_PASSWORD: root

  #ElasticSearch
  elastic_db:
    container_name: elastic_db
    image: "bitnami/elasticsearch"
    volumes:
      - ./database/sql:/usr/share/elasticsearch/data
    expose: ["9300"]
#---------------------------
#MONITORING
#---------------------------
