@startuml
!include https://raw.githubusercontent.com/ptrkcsk/one-dark-plantuml-theme/v1.0.0/theme.puml

participant Actor
Actor -> RegisterUserController : registerUser
activate RegisterUserController
RegisterUserController -> RegisterUserService : registerUser
activate RegisterUserService
RegisterUserService -> UserSqlRepository : findByEmail
activate UserSqlRepository
UserSqlRepository --> RegisterUserService
deactivate UserSqlRepository
create EmailAlreadyTakenExc
RegisterUserService -> EmailAlreadyTakenExc : new
activate EmailAlreadyTakenExc
EmailAlreadyTakenExc --> RegisterUserService
deactivate EmailAlreadyTakenExc
RegisterUserService -> PasswordEncoder : hashPwd
activate PasswordEncoder
PasswordEncoder --> RegisterUserService
deactivate PasswordEncoder
RegisterUserService -> ConfirmationTokenGeneratorService : generateConfirmationToken
activate ConfirmationTokenGeneratorService
create ConfirmationToken
ConfirmationTokenGeneratorService -> ConfirmationToken : new
activate ConfirmationToken
ConfirmationToken --> ConfirmationTokenGeneratorService
deactivate ConfirmationToken
ConfirmationTokenGeneratorService --> RegisterUserService
deactivate ConfirmationTokenGeneratorService
RegisterUserService -> EmailSenderService : sendRegistrationEmail
activate EmailSenderService
EmailSenderService -> EmailSenderService : sendEmail
activate EmailSenderService
EmailSenderService --> EmailSenderService
deactivate EmailSenderService
EmailSenderService --> RegisterUserService
deactivate EmailSenderService
RegisterUserService --> RegisterUserController
deactivate RegisterUserService
return
@enduml