@startuml
abstract class com.backend.securitygw.dataobject.aentity.PrivateUserDataAbs {
- String email
}
class com.backend.securitygw.dataobject.request.RegistrationRequest {
- String password
}
class com.backend.securitygw.dataobject.sqlentity.UserSqlEntity {
- Long id
- String hashedPassword
- String hashedPasswordSalt
- AppUserRole appUserRole
- Boolean isLocked
- Boolean isEnabled
}
abstract class com.backend.securitygw.dataobject.aentity.PublicUserDataAbs {
- String firstName
- String lastName
}
interface com.backend.securitygw.dataobject.sqlrepository.ConfirmationTokenSqlRepository {
~ Optional<ConfirmationToken> findByToken(String)
}
interface com.backend.securitygw.dataobject.sqlrepository.UserSqlRepository {
~ Optional<UserSqlEntity> findByEmail(String)
}
class com.backend.securitygw.dataobject.sqlentity.ConfirmationToken {
- Long id
- String token
- LocalDateTime createdAt
- LocalDateTime expiredAt
- LocalDateTime confirmedAt
- ConfirmationTokenType confirmationTokenType
- UserSqlEntity appUser
}
class com.backend.securitygw.dataobject.response.JwtDatagram {
}
class com.backend.securitygw.dataobject.request.UserCurrentCredential {
- String currentEmail
- String currentPwd
}
class com.backend.securitygw.dataobject.request.ChangeEmailRequest {
- String newEmail
}
class com.backend.securitygw.dataobject.request.ChangePasswordRequest {
- String newPwd
}


com.backend.securitygw.dataobject.aentity.PublicUserDataAbs <|-- com.backend.securitygw.dataobject.aentity.PrivateUserDataAbs
com.backend.securitygw.dataobject.aentity.PrivateUserDataAbs <|-- com.backend.securitygw.dataobject.request.RegistrationRequest
com.backend.securitygw.dataobject.aentity.PrivateUserDataAbs <|-- com.backend.securitygw.dataobject.sqlentity.UserSqlEntity
org.springframework.data.repository.CrudRepository <|-- com.backend.securitygw.dataobject.sqlrepository.ConfirmationTokenSqlRepository
org.springframework.data.repository.CrudRepository <|-- com.backend.securitygw.dataobject.sqlrepository.UserSqlRepository
com.backend.securitygw.dataobject.aentity.PublicUserDataAbs <|-- com.backend.securitygw.dataobject.response.JwtDatagram
com.backend.securitygw.dataobject.request.UserCurrentCredential <|-- com.backend.securitygw.dataobject.request.ChangeEmailRequest
com.backend.securitygw.dataobject.request.UserCurrentCredential <|-- com.backend.securitygw.dataobject.request.ChangePasswordRequest
@enduml