@startuml
class com.backend.securitygw.dataobject.request.ForgotPasswordRequest {
~ String token
~ String newPwd
~ ConfirmationTokenType confirmationTokenType
}
class com.backend.securitygw.dataobject.request.RegistrationRequest {
- String password
}
class com.backend.securitygw.dataobject.request.AskEmailPasswordForgotRequest {
- String emailToSend
}
class com.backend.securitygw.dataobject.request.UserCurrentCredential {
- String currentEmail
- String currentPwd
}
class com.backend.securitygw.dataobject.request.ChangeEmailRequest {
- String newEmail
}
class com.backend.securitygw.dataobject.request.ChangePasswordRequest {
- String newPwd
}


com.backend.securitygw.dataobject.aentity.PrivateUserDataAbs <|-- com.backend.securitygw.dataobject.request.RegistrationRequest
com.backend.securitygw.dataobject.request.UserCurrentCredential <|-- com.backend.securitygw.dataobject.request.ChangeEmailRequest
com.backend.securitygw.dataobject.request.UserCurrentCredential <|-- com.backend.securitygw.dataobject.request.ChangePasswordRequest
@enduml